spring:
  application:
    name: FinSoft
  datasource:
    url: ${URL_DB}
    username: ${U_DB}
    password: ${P_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
springdoc:
   api-docs:
     path: /v3/api-docs
   swagger-ui:
     path: /swagger-ui.html